version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'the_weather'
      MYSQL_ALLOW_EMTY_PASSWORD: '1'
    expose:
      "3306"
    ports:
      "3306:3306"
  mysql:
    container_name: "mysql"
    build: .    
    ports:
      "8000:8000"
    depends_on:
      mysql-db
